name: Move issue to complete
on:
  pull_request:
    types:
      - closed
jobs:
  move-closed-issue-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: refinement
          column: Complete
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
